/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package apiaula1ex;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner teclado = new Scanner(System.in);
        ArrayList<Integer> lista = new ArrayList<>();
        ArrayList<Integer> lista2 = new ArrayList<>();

        int n=0;
        while(true){
            n=teclado.nextInt();
            if(n==999){
                break;
            }
            lista.add(n);
            lista2.addFirst(n);
        }
        Collections.sort(lista);
        System.out.println(lista);
        System.out.println(lista2);
    }
}
