/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main.java.questao2;
public class App {
    public static void main(String[] args) {
        Horario hora1 = new Horario(24, 60, 60);
        Horario hora2 = new Horario(12, 30, 30);
        System.out.println(hora1.extenso());
        System.out.println(hora1.segundos());
        System.out.println(hora2.segundos());
        System.out.println(hora1.diferenca(hora2));
    }
}