/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package agenda;

public class App {
    public static void main(String[] args) {
        Agenda agenda1 = new Agenda();
        Contato contato1 = new Contato();
        agenda1.addContato(contato1);
        ageda1.add
    }
}
