/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package agenda;
import java.time.LocalDate;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Agenda agenda1 = new Agenda();
        menu(agenda1);
    }

    public static void menu(Agenda agenda1){
        Scanner teclado = new Scanner(System.in);
        while(true){
            switch (teclado.nextLine()) {
                System.out.println("Entre com o nome, sobrenome, dia, mês e ano");
                case "Adicionar Contato":
                    agenda1.addContato(new Contato(teclado.nextLine(), teclado.nextLine(), LocalDate.of(teclado.next(), teclado.next(), teclado.next())));
                    break;

                case "Adicionar Telefone":
                System.out.println("Entre com o rótulo, número e contato;");
                    agenda1.addTelefone(teclado.next(), teclado.next(), agenda1.);
                    break;

                case "Adicionar Email":
                System.out.println("Entre com o rótulo, email e contato;");
                    agenda1.addEmail("casa", "gustavao", gustavo);
                    break;
                
                case "Remover Telefone":
                System.out.println("Entre com o rótulo, número e contato;");
                    agenda1.removeEmail(null, gustavo);
                    break;

                case "Remover Email":
                System.out.println("Entre com o rótulo, email e contato;");
                agenda1.removeTelefone(null, gustavo);
                    break;

                case "Atualizar Telefone":
                System.out.println("Entre com o rótulo, número e contato;");
                    agenda1.updateTelefone(null, null, gustavo);
                    break;

                case "Atualizar Email":
                    agenda1.updateEmail(null, null, gustavo);
                    break;
                default:
                    break;
            }
        }
    }
}
