/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package introduçao_ao_paradigma;
import java.util.Random;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner teclado = new Scanner(System.in);
        Batata buzz = new Batata();
        System.out.println("--------------------------------------");
        System.out.println("atirar; atira");
        System.out.println("retrair; retrai/abaixa capacete");
        System.out.println("fala; fala");
        System.out.println("braco; golpear");
        String ler = new String();
        while(true){
            ler = teclado.nextLine();
            if(ler.equals("atirar")){
                System.out.println(buzz.atirar());
                System.out.println("--------------------------------------");
            } 
            if(ler.equals("retrair")){
                System.out.println(buzz.retraircapacete());
                System.out.println("--------------------------------------");
            } 
            if(ler.equals("braco")){
                System.out.println(buzz.golpeando());
                System.out.println("--------------------------------------");
            } 
            if(ler.equals("fala")){
                Random r = new Random();
                System.out.println(buzz.falar(r.nextInt(5)));
                System.out.println("--------------------------------------");
            }
        }
    }
}
