/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package introduçao_ao_paradigma;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner teclado = new Scanner(System.in);
        Batata buzz = new Batata();
        System.out.println("--------------------------------------");
        System.out.println("atirar; atira");
        System.out.println("retrair; retrai/abaixa capacete");
        System.out.println("fala; fala");
        while(true){
            if(teclado.nextLine().equals("atirar")){
                buzz.atirar();
            } else {
            } if(teclado.nextLine().equals("retrair")){
                buzz.retraircapacete();
            } else{ 
            } if(teclado.nextLine().equals("fala")){
                System.out.println("insira um valor de 1 à 6 para a fala");
                buzz.falar(teclado.nextInt());
            } else{
                teclado.nextLine();
            }
        }
    }
}
