/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package desenho;

import java.awt.Color;

import edu.princeton.cs.algs4.Draw;

public class App {
    public static void main(String[] args) {
        System.out.println();
        Draw draw = new Draw();
            draw.setPenColor(Color.blue);
            draw.setCanvasSize(800, 600);
            draw.setYscale(0,800);
            draw.setXscale(0, 600);
            draw.picture(300, 400, "baixado.jpeg", 300, 200, 0);;
    }
}
