/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab;

public class App {
    public static void main(String[] args) {
        Caneta c = new Caneta();
        c.setNivelTinta(300);
        System.out.println(c.getCor());
        System.out.println(c.getNivelTinta());
        Caneta c2 = new Caneta(30, "verde");
        System.out.println(c2.getCor());
        System.out.println(c2.getNivelTinta());
    }
}
