/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package carro;

import java.util.ArrayList;

public class App {
    public static void main(String[] args) {
        System.out.println("Olá");
        Carro carro = new Carro("fusca", "azul", new Motor(30, 40));

        carro.setMotor(new Motor(70,2500));

        carro = new Carro("Uno", "branco", new Motor(9000,4353));

        ArrayList<Motor> motores = new ArrayList<>();
        motores.add(carro.getMotor());
        motores.add(new Motor(39,43));
        motores.add(new Motor(4, 15));
    }
}
