/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projetopratico;

import java.util.Scanner;
import java.util.ArrayList;

import main.java.projetopratico.Carrinho;
import main.java.projetopratico.Catalogo;
import main.java.projetopratico.Item;

public class App {

    public static void listarCat(Catalogo cat){

    }
    public static void novoProd(Catalogo cat, Item item){
        
    }
    public static void iniciarVenda(){
        
    }
    public static void repor(){
        
    }

    public static void main(String[] args) {
        Scanner teclado = new Scanner(System.in);
        Carrinho carrinho = new Carrinho();
        Catalogo catalogo = new Catalogo();
        while (true) {
            System.out.printf(
                    "1. Listar catálogo de prod\n2. Adicionar novo produto\n3. Iniciar venda\n4. Repôr estoque\n5. Sair\nQual opção deseja?",
                    args);
            switch (teclado.nextInt()) {
                case 1:
                    listarCat(catalogo);
                    break;
                case 2:
                    System.out.println("Entre com o preco, a quantidade e o nome do produto novo;");
                    String[] novoitem = teclado.next().split(" ");
                    novoProd(catalogo, new Item(Integer.parseInt(novoitem[0]), Integer.parseInt(novoitem[1]), novoitem[2]));
                    break;
                case 3:
                    iniciarVenda();
                    break;
                case 4:
                    repor();
                    break;
                case 5:
                    break;
                default:
                    break;
            }
        }
    }
}
